
import { Schoolbell } from "next/font/google";
import "./globals.css";

const schoolbell_init = Schoolbell({
  subsets:['latin'],
  weight:'400',
  variable:"--font-schoolbell"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={schoolbell_init.variable}>{children}</body>
    </html>
  );
}
